.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "AG" "1" "January 2012" "" ""
.
.SH "NAME"
\fBag\fR \- The Silver Searcher\. Like ack, but faster\.
.
.SH "SYNOPSIS"
\fBag\fR [\fIoptions\fR] PATTERN PATH
.
.SH "DESCRIPTION"
Recursively search for PATTERN in PATH\. Like grep or ack, but faster\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-ackmate\fR: Output results in a format parseable by AckMate\.
.
.IP "\(bu" 4
\fB\-A \-\-after\fR [LINES]: Print lines before match\.
.
.IP "\(bu" 4
\fB\-B \-\-before\fR [LINES]: Print lines after match\.
.
.IP "\(bu" 4
\fB\-\-[no]break\fR: Print a newline between matches in different files\. Enabled by default\.
.
.IP "\(bu" 4
\fB\-\-[no]color\fR: Print color codes in results\. Enabled by default\.
.
.IP "\(bu" 4
\fB\-\-column\fR: Print column numbers in results\.
.
.IP "\(bu" 4
\fB\-C \-\-context\fR [LINES]: Print lines before and after matches\.
.
.IP "\(bu" 4
\fB\-D \-\-debug\fR: Ridiculous debugging\. Probably not useful\.
.
.IP "\(bu" 4
\fB\-f \-\-follow\fR: Follow symlinks\.
.
.IP "\(bu" 4
\fB\-\-[no]group\fR:
.
.IP "\(bu" 4
\fB\-G\fR, \fB\-\-file\-search\-regex\fR
.
.IP "\(bu" 4
\fB\-i\fR, \fB\-\-ignore\-case\fR
.
.IP "\(bu" 4
\fB\-\-invert\-match\fR
.
.IP "\(bu" 4
\fB\-\-[no]heading\fR
.
.IP "\(bu" 4
\fB\-\-literal\fR: Do not parse PATTERN as a regular expression\. Try to match it literally\.
.
.IP "\(bu" 4
\fB\-\-search\-binary\fR: Search binary files for matches\.
.
.IP "\(bu" 4
\fB\-\-stats\fR: Print stats (files scanned, time taken, etc)
.
.IP "" 0
.
.SH "IGNORING FILES"
Ag will ignore files matched by patterns in \.gitignore, \.hgignore, or \.aginore\. Ag also ignores binary files by default\.
.
.SH "EXAMPLES"
\fBag \-i foo /bar/\fR: Find matches for "foo" in path /bar/\.
.
.SH "SEE ALSO"
grep(1)
